# Generated by Django 4.1.6 on 2023-02-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_api', '0003_alter_department_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
